.TH WAVCLI 1 "2022-04-10"
.SH NAME
wavcli \- CLI to losslessly split and merge WAV/MP2/MP3/OGG files
.SH SYNOPSIS
.B wavcli
.RI [list|gen|info|merge]
<options>
.SH DESCRIPTION
.B wavcli
is the command-line interface for wavbreaker, and is missing a cool manpage.
.PP
Previously,
.B wavinfo(1),
.B wavmerge(1)
and
.B wavgen(1)
were separate utilities, these are now available as sub-commands.
.PP
.SH AUTHOR
wavbreaker was initially written by Timothy D. Robinson <tdrobinson@huli.org>.
This version is currently maintained by Thomas Perl <m@thp.io>.
.PP
.SH HOMEPAGE
https://wavbreaker.sourceforge.io/
.PP
.SH SOURCE CODE
https://github.com/thp/wavbreaker
.PP
.SH SEE ALSO
.BR wavbreaker (1).
