.TH WAVBREAKER 1 "2007-04-20"
.SH NAME
wavbreaker \- A tool to split wave files into multiple chunks
.SH SYNOPSIS
.B wavbreaker
.RI [filename.wav]
.SH DESCRIPTION
.B wavbreaker
is a graphical tool to split wave files into multiple chunks. 
You can start
.B wavbreaker
without any command line arguments or specify the filename of 
a single wave file, which will the be loaded on startup.
.PP
.SH SEE ALSO
.BR wavmerge (1),
.BR wavinfo (1).
.SH AUTHOR
wavbreaker was initially written by Timothy D. Robinson <tdrobinson@huli.org>.
This version is currently maintained by Timothy D. Robinson and Thomas Perl at
http://wavbreaker.sourceforge.net/.
