.TH WAVINFO 1 "2007-04-20"
.SH NAME
wavinfo \- Display format information for wave files
.SH SYNOPSIS
.B wavinfo
.RI file1.wav
[file2.wav]
[...]
.SH DESCRIPTION
.B wavinfo
displays information about wave files you pass to it on the command line.
This includes information about the sampling rate and bit rate used.
.PP
.SH SEE ALSO
.BR wavbreaker (1),
.BR wavmerge (1).
.SH AUTHOR
wavbreaker was initially written by Timothy D. Robinson.
This version is currently maintained by Timothy D. Robinson and Thomas Perl at
http://wavbreaker.sourceforge.net/.
