.TH WAVMERGE 1 "2007-04-20"
.SH NAME
wavmerge \- Merge multiple wave files into a single file
.SH SYNOPSIS
.B wavmerge
.RI [-o
merged.wav]
file1.wav
file2.wav
[...]
.SH DESCRIPTION
.B wavmerge
can merge wave files that are in the same format (i.e. same sample rate, 
same bits per sample, ...). If you want to merge wave files from different
formats, you will have to convert them to the same format using, for example, 
.BR sox(1).
.PP
.SH OPTIONS
.TP
\fB\-o \fImerged.wav\fR
Specify the filename of the merged wave file; if not specified,
\fBmerged.wav\fR will be used as the filename for the output
.SH SEE ALSO
.BR wavbreaker (1),
.BR wavinfo (1),
.BR sox (1).
.SH AUTHOR
wavbreaker was initially written by Timothy D. Robinson.
This version is currently maintained by Timothy D. Robinson and Thomas Perl at
http://wavbreaker.sourceforge.net/.
