name: wavbreaker
title: wavbreaker
icon: data/net.sourceforge.wavbreaker.svg
grade: stable
license: GPL-2.0
version: '0.16'
summary: GUI tool to split WAV and MP3 files
description: |
    This application's purpose in life is to take a WAV file
    and break it up into multiple WAV files. It makes a
    clean break at the correct position to burn the files to
    an Audio CD without any dead air between the tracks.

confinement: strict
base: core24

parts:
  wavbreaker:
      plugin: meson
      source-type: local
      source: .
      meson-parameters: ["--prefix=/usr"]
      build-packages:
          - meson
          - ninja-build
          - libao-dev
          - libmpg123-dev
          - libcue-dev
      stage-packages:
          - libao4
          - libmpg123-0
          - libcue2
slots:
    wavbreaker-dbus-name:
        interface: dbus
        bus: session
        name: net.sourceforge.wavbreaker
apps:
    wavbreaker:
        command: usr/bin/wavbreaker
        extensions: [gnome]
        plugs:
            - gsettings
            - home
            - network-bind
        slots:
            - wavbreaker-dbus-name
        desktop: usr/share/applications/net.sourceforge.wavbreaker.desktop
    wavcli:
      # FIXME: this is currently broken (undefined symbol: g_assertion_message_cmpint)
      command: usr/bin/wavcli
